version: '3.5'

services:
  webapp:
    image: quizapp
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/quiz?schema=public
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - quiz_backend
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quiz
    restart: unless-stopped
    networks:
      - quiz_backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  quiz_backend:
